name: Macos build

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '01 01 * * 6'    # Run every Saturday

jobs:

  list:
    name: list available perl versions
    runs-on: macos-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - id: set-matrix
        name: list available perl versions
        shell: perl {0}
        run: |
          use Actions::Core;

          print "Version available\n";
          my @versions = perl_versions();
          for my $v (@versions) {
            print "\t$v\n";
          }
          # Don't want anything less then 5.8
          @versions = grep { ! /^5\.6\.*/ } @versions;
          set_output(matrix => {perl => [@versions]});
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  run:
    runs-on: macos-latest
    needs: list
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.list.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v6
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Perl version
        run: perl -V
      - name: Unzip version
        run: unzip -h
      - name: Syntax Check
        run: perl -c fix-onedrive-zip
      - name: Test
        run: prove -v test
